import { createRequestHandler } from "@react-router/cloudflare";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - the server build file is generated by `react-router build`
import * as build from "../build/server";

export const onRequest = createRequestHandler({
	build,
});
