extends:
  - next
  - next/core-web-vitals
  - prettier

plugins:
  - 'unused-imports'
  - '@typescript-eslint'

rules:
  # typescript-eslint
  '@typescript-eslint/no-unused-vars': error

  # eslint-plugin-react-hooks
  react-hooks/rules-of-hooks: error

  # eslint-plugin-react
  react/no-access-state-in-setstate: error
  react/no-array-index-key: warn
  react/no-children-prop: error
  react/no-danger: warn
  react/no-danger-with-children: error
  react/no-deprecated: error
  react/no-direct-mutation-state: error
  react/no-render-return-value: error
  react/no-string-refs: error
  react/no-typos: error
  react/no-unescaped-entities: error
  react/no-unknown-property: error
  react/no-unstable-nested-components: [warn, { allowAsProps: true }]
  react/react-in-jsx-scope: off
  react/require-render-return: error
  react/self-closing-comp: warn
  react/style-prop-object: error
  react/void-dom-elements-no-children: error

  # eslint-plugin-react jsx-specific
  react/jsx-boolean-value: warn
  react/jsx-fragments: warn
  react/jsx-no-duplicate-props: error
  react/jsx-no-script-url: error
  react/jsx-no-undef: error
  react/jsx-no-useless-fragment: warn
  react/jsx-pascal-case: warn
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
  react/jsx-curly-brace-presence: [error, { props: never, children: never }]
  react/jsx-key:
    [error, { checkFragmentShorthand: true, checkKeyMustBeforeSpread: true }]

  # import
  unused-imports/no-unused-imports: warn
  no-restricted-imports:
    - error
    - paths:
        # Avoid importing React (no need)
        - name: react
          importNames: [default]
          message: No need to import React, please remove it.
  import/order:
    - error
    - newlines-between: always
      groups:
        - builtin
        - external
        - internal
        - unknown
        - parent
        - sibling
        - index
        - type
