services:
  production:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    volumes:
      - /app/node_modules
      - .env/:/usr/src/app/.env
    environment:
      - NODE_ENV=production

    ports:
      - 3000:3000

    develop:
      watch:
        - action: rebuild
          path: Dockerfile

        - action: rebuild
          path: docker-compose.yml

