encryptionsalt: v1:Gdj9op3TwXU=:v1:kDnyl22pMO9mQbYf:8Z2dtUWLJir5VNDyjHZcmQVY9MxFGg==
config:
  podcodar:accountId: 9ccff81da5d7c234138d96989610537d
  podcodar:zoneId: ec5904d9f2d5278ff1ecaf0ca2b71808
  podcodar:environment: dev
