import Head from 'next/head'

function Metadata() {
  return (
    <div>
      <Head>
        <title>PodCodar Code School</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/svg+xml" href="/images/favicon.svg" />
      </Head>
    </div>
  )
}

export default Metadata
