name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cloudflare
    timeout-minutes: 20
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.sha }}

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Applying infrastructure 🚀
        uses: pulumi/actions@v6
        with:
          command: up
          work-dir: infra
          stack-name: dev
          cloud-url: ${{ secrets.PULUMI_BACKEND_URL }}
        env:
          AWS_REGION: auto
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
