# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy

concurrency:
  group: production    # optional: ensure only one action runs at a time
  cancel-in-progress: true

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}:latest
  TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
  TURSO_CONNECTION_URL: ${{ secrets.TURSO_CONNECTION_URL }}

jobs:


  build-docker:
    name: Build Docker image locally
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: login to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} --build-arg TURSO_AUTH_TOKEN=${{ secrets.TURSO_AUTH_TOKEN }} --build-arg TURSO_CONNECTION_URL=${{ secrets.TURSO_CONNECTION_URL }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}

  deploy:
    name: Deploy fly.io app
    runs-on: ubuntu-latest
    environment: production
    needs: build-docker
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --ha=false --remote-only -i ${{ env.IMAGE_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
