# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy

concurrency:
  group: production    # optional: ensure only one action runs at a time
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy fly.io app
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
          TURSO_CONNECTION_URL: ${{ secrets.TURSO_CONNECTION_URL }}
