name: Run Tests

on:
  pull_request:
    # all branches
    branches:
      - '*'
  push:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Run unit-tests
        run: |
          bun install --frozen-lockfile && bun run test

  integration-tests:
    timeout-minutes: 300
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile && bun run playwright install --with-deps

        # NOTE: using hard-coded URL
      # - name: Waiting for 200 from the Vercel Preview
      #   uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
      #   id: waitFor200
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     max_timeout: 300

      # access preview url
      - name: Inject testing URL
        run: echo "TEST_URL=https://podcodar.org" >> $GITHUB_ENV
        # NOTE: using hard-coded URL
        # run: echo "TEST_URL=${{steps.waitFor200.outputs.url}}" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: bun run e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 2
